# Generated by Django 4.2.4 on 2024-08-10 13:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("simplejwtauth", "0001_initial"),
        ("crmpipeline", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="id",
            new_name="activity_id",
        ),
        migrations.RenameField(
            model_name="deal",
            old_name="unique_id",
            new_name="deal_id",
        ),
        migrations.RenameField(
            model_name="lead",
            old_name="id",
            new_name="lead_id",
        ),
        migrations.RenameField(
            model_name="pipeline",
            old_name="id",
            new_name="pipeline_id",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="team_member",
        ),
        migrations.RemoveField(
            model_name="task",
            name="id",
        ),
        migrations.AddField(
            model_name="deal",
            name="sales_officer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="simplejwtauth.salesofficer",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
