# Generated by Django 4.2.4 on 2024-07-31 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stage",
            name="move_criteria",
        ),
    ]
