# Generated by Django 4.2.4 on 2024-08-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dealpipeline",
            name="deal",
        ),
        migrations.DeleteModel(
            name="DealRequirement",
        ),
        migrations.DeleteModel(
            name="EmaiLog",
        ),
        migrations.DeleteModel(
            name="HeadOfSales",
        ),
        migrations.DeleteModel(
            name="LeadsDataUpload",
        ),
        migrations.RemoveField(
            model_name="merchantdealpipeline",
            name="merchant",
        ),
        migrations.DeleteModel(
            name="Report",
        ),
        migrations.RemoveField(
            model_name="taskcomment",
            name="parent_comment",
        ),
        migrations.RemoveField(
            model_name="taskcomment",
            name="sales_officer",
        ),
        migrations.RemoveField(
            model_name="taskcomment",
            name="task",
        ),
        migrations.DeleteModel(
            name="TaskSchedule",
        ),
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="member",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="merchant",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="role",
        ),
        migrations.AlterModelOptions(
            name="teammemberrole",
            options={
                "verbose_name": "TEAM MEMBER ROLE",
                "verbose_name_plural": "TEAM MEMBER ROLES",
            },
        ),
        migrations.DeleteModel(
            name="DealPipeline",
        ),
        migrations.DeleteModel(
            name="MerchantDealPipeline",
        ),
        migrations.DeleteModel(
            name="TaskComment",
        ),
        migrations.DeleteModel(
            name="TeamMember",
        ),
    ]
