# Generated by Django 4.2.4 on 2024-07-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0002_remove_stage_move_criteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealprogression",
            name="unique_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
