# Generated by Django 4.2.4 on 2024-08-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0002_rename_id_activity_activity_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stage",
            old_name="id",
            new_name="stage_id",
        ),
    ]
