# Generated by Django 4.2.4 on 2024-07-31 22:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0003_dealprogression_unique_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="pipeline",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="pipeline",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="pipeline_type",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="sales_officer",
        ),
        migrations.RemoveField(
            model_name="pipeline",
            name="automation_enabled",
        ),
        migrations.RemoveField(
            model_name="pipeline",
            name="is_default",
        ),
        migrations.RemoveField(
            model_name="pipeline",
            name="merchant",
        ),
        migrations.RemoveField(
            model_name="pipeline",
            name="salesofficer",
        ),
        migrations.RemoveField(
            model_name="pipeline",
            name="stages",
        ),
        migrations.RemoveField(
            model_name="stage",
            name="automation_enabled",
        ),
        migrations.RemoveField(
            model_name="stage",
            name="is_new_merchant",
        ),
        migrations.AddField(
            model_name="pipeline",
            name="pipeline_type",
            field=models.CharField(
                choices=[("DEFAULT", "DEFAULT"), ("CUSTOM", "CUSTOM")],
                default="DEFAULT",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="stage",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crmpipeline.pipeline",
            ),
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email_address", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("company", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "label",
                    models.CharField(
                        choices=[("HOT", "HOT"), ("WARM", "WARM"), ("COLD", "COLD")],
                        default="COLD",
                        max_length=100,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crmpipeline.stage",
                    ),
                ),
            ],
        ),
    ]
