# Generated by Django 4.2.4 on 2024-07-31 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0004_remove_activity_pipeline_remove_deal_pipeline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="deal",
        ),
    ]
