# Generated by Django 4.2.4 on 2024-08-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0005_remove_stage_pipeline_pipeline_stages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="stage",
        ),
        migrations.AddField(
            model_name="stage",
            name="activity",
            field=models.ManyToManyField(blank=True, to="crmpipeline.activity"),
        ),
    ]
