# Generated by Django 4.2.4 on 2024-08-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0007_alter_activity_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="stages",
            field=models.ManyToManyField(
                blank=True, related_name="stage", to="crmpipeline.stage"
            ),
        ),
    ]
