# Generated by Django 4.2.4 on 2024-08-16 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0008_activity_stages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="stages",
            new_name="stage_id",
        ),
    ]
