# Generated by Django 4.2.4 on 2024-08-16 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("simplejwtauth", "0002_alter_salesofficer_sales_lead"),
        ("crmpipeline", "0011_remove_task_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="sales_officer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="simplejwtauth.salesofficer",
            ),
        ),
    ]
