# Generated by Django 4.2.4 on 2024-08-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0012_lead_sales_officer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="trail",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
