# Generated by Django 4.2.4 on 2024-08-18 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0013_alter_deal_trail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="stage_id",
        ),
        migrations.AddField(
            model_name="activity",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crmpipeline.deal",
            ),
        ),
    ]
