# Generated by Django 4.2.4 on 2024-08-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0015_remove_stage_activity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deal",
            options={"verbose_name": "DEAL", "verbose_name_plural": "DEALS"},
        ),
        migrations.RemoveField(
            model_name="task",
            name="deal_progression",
        ),
    ]
