# Generated by Django 4.2.4 on 2024-08-19 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0016_alter_deal_options_remove_task_deal_progression"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="task",
        ),
        migrations.RemoveField(
            model_name="task",
            name="activity_id",
        ),
        migrations.AddField(
            model_name="task",
            name="activity_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity",
                to="crmpipeline.activity",
            ),
        ),
    ]
