# Generated by Django 4.2.4 on 2024-08-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0017_remove_activity_task_remove_task_activity_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="deal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
