# Generated by Django 4.2.4 on 2024-08-20 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("simplejwtauth", "0004_alter_superadmin_options"),
        ("crmpipeline", "0018_remove_deal_created_at_alter_deal_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crmpipeline.pipeline",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="merchant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="simplejwtauth.company",
            ),
        ),
    ]
