# Generated by Django 4.2.4 on 2024-08-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0019_deal_pipeline_alter_deal_merchant"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="deal_stage",
            field=models.CharField(
                blank=True, default="New Deal", max_length=100, null=True
            ),
        ),
    ]
