# Generated by Django 4.2.4 on 2024-08-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0020_deal_deal_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="email_notifications_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
