# Generated by Django 4.2.4 on 2024-08-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0021_alter_stage_email_notifications_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pipeline",
            name="stages",
        ),
        migrations.AddField(
            model_name="stage",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crmpipeline.pipeline",
            ),
        ),
    ]
