# Generated by Django 4.2.4 on 2024-08-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0023_remove_stage_pipeline_pipeline_stages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="trail",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
