# Generated by Django 4.2.4 on 2024-08-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0024_alter_deal_trail"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DealProgression",
        ),
    ]
