# Generated by Django 4.2.4 on 2024-08-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crmpipeline", "0025_delete_dealprogression"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="expected_close_date",
        ),
        migrations.AddField(
            model_name="deal",
            name="expiry_date",
            field=models.DateTimeField(null=True),
        ),
    ]
