# Generated by Django 4.2.4 on 2024-07-28 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_name", models.CharField(max_length=255)),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
            ],
            options={
                "verbose_name": "COMPANY",
                "verbose_name_plural": "COMPANIES",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesLead",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("is_sales_lead", models.BooleanField(default=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("date_hired", models.DateField(default=django.utils.timezone.now)),
                (
                    "product_verticals",
                    models.CharField(
                        choices=[
                            ("SI", "Stock Inventory & Stock Management"),
                            ("SA", "Sales"),
                            ("SM", "Spend Management"),
                            ("HRM", "HR Management"),
                        ],
                        max_length=200,
                    ),
                ),
                ("merchants_acquired", models.IntegerField(default=0)),
                ("terminals_deployed", models.IntegerField(default=0)),
                (
                    "merchant_activation_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "overall_merchant_activation_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "revenue_generated",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "overall_revenue_generated",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "average_revenue_generated",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "overall_average_revenue_generated",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("total_transaction_volume", models.IntegerField(default=0)),
                ("total_subscription_volume", models.IntegerField(default=0)),
                (
                    "total_subscription_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("active_merchants_count", models.IntegerField(default=0)),
                ("inactive_merchants_count", models.IntegerField(default=0)),
                (
                    "customer_satisfaction_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "sales_team_performance",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_name", models.CharField(max_length=255)),
                (
                    "team_type",
                    models.CharField(
                        choices=[
                            ("PAYROLL", "PAYROLL"),
                            ("SALES", "SALES"),
                            ("SPEND_MGMT", "SPEND_MGMT"),
                            ("STOCK", "STOCK"),
                        ],
                        default="SPEND_MGMT",
                        max_length=255,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company",
                        to="users.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "TEAM",
                "verbose_name_plural": "TEAMS",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="useraccount",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "USER PROFILE",
                "verbose_name_plural": "USER PROFILES",
            },
        ),
        migrations.AddField(
            model_name="useraccount",
            name="channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USSD", "USSD"),
                    ("WEB", "WEB"),
                    ("MOBILE", "MOBILE"),
                    ("POS", "POS"),
                ],
                default="WEB",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="date created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useraccount",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="has_company",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="date updated"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="TeamMemberInvite",
            fields=[
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "TEAM MEMBER INVITATION",
                "verbose_name_plural": "TEAM MEMBER INVITATIONS",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("phone_no", models.CharField(blank=True, max_length=255, null=True)),
                ("is_registered", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("NOT_JOINED", "NOT_JOINED"),
                            ("SUSPENDED", "SUSPENDED"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "ADMIN"),
                            ("DISBURSER", "DISBURSER"),
                            ("MANAGER", "MANAGER"),
                            ("MEMBER", "MEMBER"),
                            ("OWNER", "OWNER"),
                            ("REVIEWER", "REVIEWER"),
                            ("SALES_MAN", "SALES_MAN"),
                            ("SUB_ADMIN", "SUB_ADMIN"),
                            ("SUPERVISOR", "SUPERVISOR"),
                        ],
                        default="MEMBER",
                        max_length=255,
                    ),
                ),
                ("req_no", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team",
                        to="users.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "TEAM MEMBER",
                "verbose_name_plural": "TEAM MEMBERS",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="members", to="users.teammember"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SalesOfficer",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("is_sales_officer", models.BooleanField(default=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("date_hired", models.DateField(default=django.utils.timezone.now)),
                (
                    "product_vertical",
                    models.CharField(
                        choices=[
                            ("SI", "Stock Inventory & Stock Management"),
                            ("SA", "Sales"),
                            ("SM", "Spend Management"),
                            ("HRM", "HR Management"),
                        ],
                        max_length=200,
                    ),
                ),
                ("merchants_acquired", models.IntegerField(default=0)),
                ("terminals_deployed", models.IntegerField(default=0)),
                (
                    "merchant_activation_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "revenue_generated",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "overall_revenue_generated",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "average_revenue_generated",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "overall_average_revenue_generated",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("total_transaction_volume", models.IntegerField(default=0)),
                ("total_subscription_volume", models.IntegerField(default=0)),
                (
                    "total_subscription_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("active_merchants_count", models.IntegerField(default=0)),
                ("inactive_merchants_count", models.IntegerField(default=0)),
                (
                    "customer_satisfaction_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "individual_merchant_metrics",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "merchant_acquisition_status",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "merchant_acquisition_percentage_ratio",
                    models.FloatField(default=0.0),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "sales_lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_officers",
                        to="users.saleslead",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="saleslead",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="sales_officer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.salesofficer",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="company_related_teams", to="users.team"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="default_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_company",
                to="users.company",
            ),
        ),
    ]
