# Generated by Django 4.2.4 on 2024-08-02 08:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_company_saleslead_team_alter_useraccount_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeadOfSales",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="saleslead",
            name="active_merchants_count",
        ),
        migrations.RemoveField(
            model_name="saleslead",
            name="average_revenue_generated",
        ),
        migrations.RemoveField(
            model_name="saleslead",
            name="customer_satisfaction_score",
        ),
        migrations.RemoveField(
            model_name="saleslead",
            name="inactive_merchants_count",
        ),
        migrations.RemoveField(
            model_name="saleslead",
            name="merchant_activation_rate",
        ),
        migrations.RemoveField(
            model_name="saleslead",
            name="merchants_acquired",
        ),
        migrations.RemoveField(
            model_name="saleslead",
            name="overall_average_revenue_generated",
        ),
        migrations.RemoveField(
            model_name="saleslead",
            name="overall_merchant_activation_rate",
        ),
        migrations.RemoveField(
            model_name="saleslead",
            name="overall_revenue_generated",
        ),
        migrations.RemoveField(
            model_name="saleslead",
            name="product_verticals",
        ),
        migrations.RemoveField(
            model_name="saleslead",
            name="revenue_generated",
        ),
        migrations.RemoveField(
            model_name="saleslead",
            name="sales_team_performance",
        ),
        migrations.RemoveField(
            model_name="saleslead",
            name="terminals_deployed",
        ),
        migrations.RemoveField(
            model_name="saleslead",
            name="total_subscription_value",
        ),
        migrations.RemoveField(
            model_name="saleslead",
            name="total_subscription_volume",
        ),
        migrations.RemoveField(
            model_name="saleslead",
            name="total_transaction_volume",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="active_merchants_count",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="average_revenue_generated",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="customer_satisfaction_score",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="inactive_merchants_count",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="individual_merchant_metrics",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="merchant_acquisition_percentage_ratio",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="merchant_acquisition_status",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="merchant_activation_rate",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="merchants_acquired",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="overall_average_revenue_generated",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="overall_revenue_generated",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="product_vertical",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="revenue_generated",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="terminals_deployed",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="total_subscription_value",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="total_subscription_volume",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="total_transaction_volume",
        ),
        migrations.AlterField(
            model_name="teammember",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "ADMIN"),
                    ("SALES_LEAD", "SALES_LEAD"),
                    ("MEMBER", "MEMBER"),
                    ("OWNER", "OWNER"),
                    ("SALES_OFFICER", "SALES_OFFICER"),
                ],
                default="MEMBER",
                max_length=255,
            ),
        ),
    ]
