# Generated by Django 4.2.4 on 2024-08-05 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_headofsales_user_saleslead_head_of_sales_superadmin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="default_company",
        ),
    ]
