# Generated by Django 4.2.4 on 2024-08-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_useraccount_default_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleslead",
            name="is_sales_lead",
        ),
        migrations.AddField(
            model_name="saleslead",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="saleslead",
            name="is_superuser",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="superadmin",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="superadmin",
            name="is_superuser",
            field=models.BooleanField(default=True),
        ),
    ]
