# Generated by Django 4.2.4 on 2024-08-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_saleslead_is_sales_lead_saleslead_is_staff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="headofsales",
            name="name",
        ),
        migrations.RemoveField(
            model_name="saleslead",
            name="name",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="is_sales_officer",
        ),
        migrations.RemoveField(
            model_name="salesofficer",
            name="name",
        ),
        migrations.RemoveField(
            model_name="superadmin",
            name="name",
        ),
        migrations.AddField(
            model_name="headofsales",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="headofsales",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="saleslead",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="saleslead",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="salesofficer",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="salesofficer",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="superadmin",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="superadmin",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
