# Generated by Django 4.2.4 on 2024-08-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simplejwtauth", "0002_alter_salesofficer_sales_lead"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="superadmin",
            options={
                "verbose_name": "Super Admin",
                "verbose_name_plural": "Super Admins",
            },
        ),
    ]
