# Generated by Django 4.2.4 on 2024-08-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simplejwtauth", "0003_alter_superadmin_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="superadmin",
            options={},
        ),
    ]
